CREATE TABLE `brute_force`.`users` (`cin` VARCHAR(11) NOT NULL , `nom` VARCHAR(255) NOT NULL , `prenom` VARCHAR(255) NOT NULL , `username` VARCHAR(255) NOT NULL , `email` VARCHAR(255) NOT NULL , `password` VARCHAR(255) NOT NULL , `role` INT(11) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP NULL DEFAULT NULL , PRIMARY KEY (`cin`(11))) ENGINE = InnoDB;

CREATE TABLE roles (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `role` VARCHAR(255)
);

ALTER TABLE users
ADD CONSTRAINT fk_role
FOREIGN KEY (role) REFERENCES roles(id);
